export const ADDREMOVE = {
  ADD_PERSON: "ADD_PERSON",
  REMOVE_PERSON: "REMOVE_PERSON",
};

export const HADNLECHANGE = {
  HANDLE_NAME: "HANDLE_NAME",
  HANDLE_SURNAME: "HANDLE_SURNAME",
  HANDLE_AGE: "HANDLE_AGE",
  HANDLE_EMAIL: "HANDLE_EMAIL",
};
